version: '3'
services:
  web:
    build: .
    container_name: photo_cleaner_app
    ports:
      - "5050:5000"  # 浏览器通过 http://nas-ip:5050 访问
    environment: # 设置环境变量，告诉容器内的 Python 脚本照片库路径; 如果你在 Windows 上运行 Docker，确保路径格式正确（例如：/data 对应于 Windows 的 Y: 驱动器）
          - NAS_PHOTO_DIR=/homes  # 关键：告诉 Python 容器内的照片路径
          - PUID=1026  # 在 NAS 终端输入 id 命令查看你自己的 UID
          - PGID=100   # 通常群晖的 users 组是 100
        # 👇 新增下面这两行，把 AI 模型的下载和缓存路径改到 /tmp
          - TORCH_HOME=/tmp/torch_models
          - XDG_CACHE_HOME=/tmp/cache
    volumes:
      - /volume1/homes/:/homes:rw # 重要：将你的照片库映射到容器内的 /data
    restart: unless-stopped
    user: "1026:100" # 这样容器会以你的 NAS 账号权限运行
