version: '3'
services:
  web:
    build: .
    container_name: photo_cleaner_app
    ports:
      - "5050:5000"  # 浏览器通过 http://nas-ip:5050 访问
    environment:
          - NAS_PHOTO_DIR=/data  # 关键：告诉 Python 容器内的照片路径
    volumes:
      - /volume2/docker/nas_cleaner/download:/data:rw  # 重要：将你的照片库映射到容器内的 /data
    restart: unless-stopped